### ISSUE TITLE
polymer-ui-arrow

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_ui_elements#13]
Port polymer-ui-arrow (https://github.com/Polymer/polymer-ui-elements/tree/master/polymer-ui-arrow)

**Comment by zoechi** [comment]
this is still in progress I guess.
The demo page shows now output.

**Comment by ErikGrimes** [comment]
Yea.  I'm not sure what the issue is. I stepped through it in the debugger and the element is functioning. I inspected it in chrome web tools and the styles in the element's style tag aren't being applied.  I don't see anything obviously wrong with the template though.

**Comment by zoechi** [comment]
I found a bug in asyncUpdate "!= null" should be "== null" (changed it)
But the source seems to be Dartium.
Dartium shows also an empty page with the JS polymer-ui-arrows example (works in Chrome)

**Comment by zoechi** [comment]
waiting for an answer ~~https://groups.google.com/a/dartlang.org/forum/#!newtopic/web-ui~~
https://code.google.com/p/dart/issues/detail?id=14871&thanks=14871&ts=1383761825

**Comment by ErikGrimes** [comment]
Must not have saw my changes :) I saw you removed app-element.  I think
Siggi called an app-element a 'best-practice' and I consider it a best
practice as well.  When you need an app-element and when you don't can be
confusing to new polymer users. Consistency also trumps over minor
redundancy in my book. So, I like to use the app-element pattern
consistently for all examples, redundant or not.

**Comment by ErikGrimes** [comment]
Nice catch on the Dartium!

**Comment by zoechi** [comment]
Sorry, it was not my intention to mess around so much with the code you built with much effort.
I just saw your comment that you don't know why the example won't show anything.
I didn't realize that you still changed the code.
My intention was to strip all unnecessary code to make it easier to debug or reason about.
When I tried to pull I just saw your changes and thought I could have been an attempt to try if the example maybe works out this way.

I followed the rule that I create an app-element when I would otherwise need a template element in the main page.
