### ISSUE TITLE
Aw Snap Error when mixing own polymer elements with polymer_ui_elements.

### ISSUE THREAD

**Issue by cyrillzadra** [bwu-dart-graveyard/polymer_ui_elements#59]
After I imported polymer_ui_elements from a local path and  mixed it with my own polymer elements I always receive an "Aw Snap" error. I've no clue what's the reason for this error could be. Is there somewhere more output what produces this "Aw Snap" error?

``` html
<html>
<head>
<meta charset="utf-8">
<title>Trip Manager 1000</title>
<link rel="stylesheet" href="mpismobile.css">
<script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="packages/browser/interop.js"></script>
<!-- import components -->
<link rel="import" href="packages/polymer_ui_elements/polymer_ui_pages/polymer_ui_pages.html">
<link rel="import" href="components/mpismaps.html">
<link rel="import" href="components/mpispoimgr.html">
<link rel="import" href="components/mpistripmgr.html">
</head>
<body>
  <h1>MpisMobile</h1>
  <p>Hello world from Dart!</p>   
  <polymer-ui-pages selected="0">
    <span>   
      <mpis-maps id="myMap"></mpis-maps>
    </span> 
    <span>
      <mpis-poimgr></mpis-poimgr>
    </span>
    <span>
      <mpis-tripmgr></mpis-tripmgr>
    </span>
  </polymer-ui-pages>
  <script type="application/dart" src="mpismobile.dart"></script>
  <script src="packages/browser/dart.js"></script>
</body>
</html>
```

The complete example can be found here ->
https://github.com/thomasfrick1/mpis/tree/master/MpisMobile

Thanks
Cyrill

**Comment by zoechi** [comment]
Hi Cyrill,

I have those "Aw snap" very often but most of the time on a project where I don't use polymer_(ui_)elements yet.
I found only one hint for this problem myself yet: 
Remove all breakpoints even or especially from all other Dart projects (using Darteditor breakpoints view).
It doesn't matter if the breakpoints are hit or if you use the debugger at all.

I "Aw snap" occurs again it is caused by something else.

Günter

**Comment by cyrillzadra** [comment]
Wow.. Thanks a lot! Just as you said!  I had a breakpoint in polymer_selector.dart :).
