### ISSUE TITLE
compile to javascript

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_ui_elements#6]
We need to ensure that the project and it's examples can compile to javascript.

**Comment by zoechi** [comment]
I experimented with this but pub build and build.dart won't work with the example directory even though it suits the package layout convention.
pub build and build.dart run fine (if at least an empty web directory exists) but the build directory only contains the packages directory afterwards. any ideas?
I posted a question in the Dart Misc forum: https://groups.google.com/a/dartlang.org/forum/#!topic/web-ui/jdoLc_roMLI
Do you have any ideas for a workaround?

**Comment by zoechi** [comment]
I created two packages (polymer_elements_examples, polymer_ui_elements_examples)
just to be able to build the examples.

Can you please create repositories for these so I can commit?

The packages are only needed until pub build can build the examples directory and the transformers configuration for the examples doesn't break the build of the elements anymore.

**Comment by ErikGrimes** [comment]
Sure.  You should be able to access both repos now.

Erik

**Comment by zoechi** [comment]
Ok I commited them
they contain mostly the pubspec.yaml and a link to the examples
I hope the link works when you check out the repository.

pub build should work for polymer_elements_examples
in polymer_ui_elements_examples is the problem that the build fails due to out of memory
would be interesting if this is the same for you.
